### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-claraharguindey#1]
Awesome job @claraharguindey  !!!

Here you have some tips to improve the exercise:

- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [ ] Extract the feedback painter to a function
- [x] Instead of getting the counter status from HTML, store the value into a variable, increase it in each click and paint it. This way you avoid parsing it every time and have more control.
- [x] Move variables declaration to the top of the file

Let me know if you have any doubts ;)

Go for it!!

**Comment by claraharguindey** [comment]
Thanks for the feedback, Nasiba!

I think I've made all the changes except "extract the feedback painter to a function", I'm not sure if I understand what you mean. Also, I think I haven't any ==, but maybe I have not located it. 
Let me know if I should improve anything else!! thank you! :)

**Comment by nasivuela** [comment]
Good job @claraharguindey !!!

![](https://media.giphy.com/media/8RxCFgu88jUbe/giphy.gif)

I'm closing this, but if you want more challenges you can:
- Extract the feedback painter to a function, since you are writing 4 times `feedbackContainer.innerHTML = "something";`, you could extract it to a function that accepts the message to paint as param ;)
- What about adding a restart feature when the user wins?
